"""add comunicado model

Revision ID: 960c944b52d3
Revises: dcd3654559b7
Create Date: 2026-07-09 07:07:42.948052

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '960c944b52d3'
down_revision = 'dcd3654559b7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('comunicados',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('author_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['author_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('comunicados')
    # ### end Alembic commands ###
