"""add assigned_to to reports

Revision ID: b701b7850ea5
Revises: 960c944b52d3
Create Date: 2026-07-09 07:12:43.091141

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b701b7850ea5'
down_revision = '960c944b52d3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('reports', schema=None) as batch_op:
        batch_op.add_column(sa.Column('assigned_to', sa.Integer(), nullable=True))
        batch_op.create_foreign_key('fk_reports_assigned_to', 'users', ['assigned_to'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('reports', schema=None) as batch_op:
        batch_op.drop_constraint('fk_reports_assigned_to', type_='foreignkey')
        batch_op.drop_column('assigned_to')

    # ### end Alembic commands ###
